language: node_js
node_js:
- '7'
cache:
  directories:
    - "node_modules"
install: npm install
script:
- node index.js
notifications:
  slack: buildingpipelines:PB1uV6U8DGpMFX9ZPhhboD55
    on_success: always
    on_failure: always
   email:
    - jayveyor@gmail.com
  
