language: node_js
node_js:
  - '7'
#  - 8
cache:
  directories:
    - "node_modules"
install: npm install
script:
  - node index.js
notifications:
  slack: buildingpipelines:PB1uV6U8DGpMFX9ZPhhboD55
  email:
    recipients:
      - jayveyor@gmail.com
  on_success: always
  on_failure: always


  
